### ISSUE TITLE
Downloading image_list error

### ISSUE THREAD

**Issue by XYHu122** [BIT-DA/LSG#2]
Hi. When I runned train_stage2.sh, an error occured: 
Fail to download image_list.zip from url link https://cloud.tsinghua.edu.cn/f/3d852099cc0842d58e1a/?dl=1
Please check you internet connection or reinstall DALIB by 'pip install --upgrade dalib'

I have installed the latest version of dalib (which is 0.2), so I wonder if the url provided is correct, thanks!

**Comment by singalist** [comment]
My apologies for the late reply. The urls for the datasets are changed (see https://github.com/thuml/Transfer-Learning-Library/tree/master?tab=readme-ov-file#notice-2023-08-01).

The updated urls can be found in the files of Transfer-Learning-Library:
Aircraft: https://github.com/thuml/Transfer-Learning-Library/blob/master/tllib/vision/datasets/aircrafts.py#L40
StanfordCars: https://github.com/thuml/Transfer-Learning-Library/blob/master/tllib/vision/datasets/stanford_cars.py#L40
CUB: https://github.com/thuml/Transfer-Learning-Library/blob/master/tllib/vision/datasets/cub200.py#L39

**Comment by XYHu122** [comment]
I replaced the data download files and the problem was solved, thx!
